version: "3"
services: 
    client:
        container_name: client
        build:
            context: .
            dockerfile: client/Dockerfile
        volumes: 
            # - "/client/app/node_modules"
            # - "./:/client/app"
            - ../client:/app
            - ../client/node_modules:/app/node_modules
        command: yarn start
    posts:
        container_name: posts
        build:
            context: .
            dockerfile: posts/Dockerfile
        volumes: 
            # - "/posts/app/node_modules"
            # - "./:/posts/app"
            - ../posts:/app
            - ../posts/node_modules:/app/node_modules
        command: npm start
    comments:
        container_name: comments
        build:
            context: .
            dockerfile: comments/Dockerfile
        volumes: 
            # - "/comments/app/node_modules"
            # - "./:/comments/app"
            - ../comments:/app
            - ../comments/node_modules:/app/node_modules
        command: npm start
    query:
        container_name: query
        build:
            context: .
            dockerfile: query/Dockerfile
        volumes: 
            # - "/query/app/node_modules"
            # - "./:/query/app"
            - ../query:/app
            - ../query/node_modules:/app/node_modules
        command: npm start
    moderation:
        container_name: moderation
        build:
            context: .
            dockerfile: moderation/Dockerfile
        volumes: 
            # - "/moderation/app/node_modules"
            # - "./:/moderation/app"
            - ../moderation:/app
            - ../moderation/node_modules:/app/node_modules
        command: npm start
    event-bus:
        container_name: event-bus
        build:
            context: .
            dockerfile: event-bus/Dockerfile
        volumes: 
            # - "/event-bus/app/node_modules"
            # - "./:/event-bus/app"
            - ../event-bus:/app
            - ../event-bus/node_modules:/app/node_modules
        command: npm start