version: "3"
services: 
    posts:
        container_name: posts
        image: 'node:12-alpine'
        working_dir: /app
        restart: on-failure
        ports:
            - 4000:4000
        # links: 
        #     - event-bus
        # depends_on:
        #     - event-bus
        networks:
            - my-microservice-bootcamp
        volumes: 
            - ./posts:/app
            - /app/node_modules
        command: 'sh -c "npm install && npm start"'
    comments:
        container_name: comments
        image: 'node:12-alpine'
        working_dir: /app
        build:
            context: .
            dockerfile: comments/Dockerfile
        restart: on-failure
        ports:
            - 4001:4001
        # links: 
        #     - event-bus
        # depends_on:
        #     - event-bus
        networks:
            - my-microservice-bootcamp
        volumes: 
            - ./comments:/app
            - /app/node_modules
        command: 'sh -c "npm install && npm start"'
    query:
        container_name: query
        image: 'node:12-alpine'
        working_dir: /app
        build:
            context: .
            dockerfile: query/Dockerfile
        restart: on-failure
        ports:
            - 4002:4002
        # links: 
        #     - event-bus
        # depends_on:
        #     - event-bus
        networks:
            - my-microservice-bootcamp
        volumes: 
            - ./query:/app
            - /app/node_modules
        command: 'sh -c "npm install && npm start"'
    moderation:
        container_name: moderation
        image: 'node:12-alpine'
        working_dir: /app
        build:
            context: .
            dockerfile: moderation/Dockerfile
        restart: on-failure
        ports:
            - 4003:4003
        # links: 
        #     - event-bus
        # depends_on:
        #     - event-bus
        networks:
            - my-microservice-bootcamp
        volumes: 
            - ./moderation:/app
            - /app/node_modules
        command: 'sh -c "npm install && npm start"'
    event-bus:
        container_name: event-bus
        image: 'node:12-alpine'
        working_dir: /app
        build:
            context: .
            dockerfile: event-bus/Dockerfile
        restart: on-failure
        ports:
            - 4005:4005
        networks:
            - my-microservice-bootcamp
        volumes: 
            - ./event-bus:/app
            - /app/node_modules
        command: 'sh -c "npm install && npm start"'
    client:
        container_name: client
        working_dir: /app
        build:
            # context: .
            # dockerfile: client/Dockerfile
            context: ./client
        restart: on-failure
        ports:
            - 3000:3000
        # links: 
        #     - posts
        #     - comments
        # depends_on:
        #     - posts
        #     - comments
        networks:
            - my-microservice-bootcamp
        volumes: 
            # - ./client:/app
            # - ./client/node_modules:/app/node_modules
            - ./client:/app
            - /app/node_modules
        command: 'sh -c "yarn && yarn start"'

networks:
    my-microservice-bootcamp:
        driver: bridge